name: License Check

on:
    push:
        branches:
            - main
            - develop
        paths:
            - 'composer.lock'
            - 'composer.json'
    pull_request:
        paths:
            - 'composer.lock'
            - 'composer.json'

jobs:
    license-check:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                operating-system: [ 'ubuntu-latest' ]
                php-versions: [ '8.4' ]
                dependency-stability: [ 'prefer-none' ]

        name: P${{ matrix.php-versions }} - ${{ matrix.operating-system}}

        steps:
            -   uses: actions/checkout@v6
            -   name: Install PHP versions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    tools: "composer:v2"

            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction

            - name: Run license check
              run: composer run license-check
